{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "b6f875b5-2a73-4834-a4bb-bfde38bb7145",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.preprocessing.image import ImageDataGenerator\n",
    "from tensorflow.keras.applications import MobileNetV2\n",
    "from tensorflow.keras.models import Model, load_model\n",
    "from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout\n",
    "import os\n",
    "from PIL import Image\n",
    "import cv2\n",
    "import streamlit as st\n",
    "from deepface import DeepFace\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Load the trained age classifier model\n",
    "model_path = \"/Users/usufahmed/Desktop/gender_app/faces/models/age_classifier.keras\"\n",
    "if not os.path.exists(model_path):\n",
    "    raise FileNotFoundError(f\"Model file {model_path} not found. Please train and save the model first.\")\n",
    "age_model = load_model(model_path)\n",
    "\n",
    "# Define image parameters\n",
    "IMG_SIZE = (224, 224)\n",
    "BATCH_SIZE = 32\n",
    "\n",
    "# Function to preprocess and predict age group\n",
    "def predict_age_group(image_path):\n",
    "    try:\n",
    "        img = Image.open(image_path).convert('RGB')\n",
    "        img = img.resize(IMG_SIZE)\n",
    "        img_array = np.expand_dims(np.array(img) / 255.0, axis=0)\n",
    "        prediction = age_model.predict(img_array)\n",
    "        class_names = ['MIDDLE', 'OLD', 'YOUNG']  # Adjust based on your dataset\n",
    "        predicted_class = class_names[np.argmax(prediction)]\n",
    "        return predicted_class, prediction[0]\n",
    "    except Exception as e:\n",
    "        return f\"Error predicting age: {e}\", None\n",
    "\n",
    "# Function to predict gender using DeepFace\n",
    "def predict_gender(image_path):\n",
    "    try:\n",
    "        result = DeepFace.analyze(img_path=image_path, actions=['gender'], enforce_detection=False)\n",
    "        gender_probs = result[0]['gender']\n",
    "        return gender_probs\n",
    "    except Exception as e:\n",
    "        return {\"Error\": str(e)}\n",
    "\n",
    "# Function to generate Grad-CAM heatmap for age model\n",
    "def grad_cam(model, img_array, last_conv_layer_name=\"block_16_project\"):\n",
    "    grad_model = Model([model.inputs], [model.get_layer(last_conv_layer_name).output, model.output])\n",
    "    with tf.GradientTape() as tape:\n",
    "        conv_outputs, predictions = grad_model(img_array)\n",
    "        class_idx = np.argmax(predictions[0])\n",
    "        loss = predictions[:, class_idx]\n",
    "    grads = tape.gradient(loss, conv_outputs)\n",
    "    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))\n",
    "    conv_outputs = conv_outputs[0]\n",
    "    heatmap = tf.reduce_mean(tf.cast(conv_outputs, tf.float32) * pooled_grads, axis=-1)\n",
    "    heatmap = np.maximum(heatmap, 0) / np.max(heatmap)\n",
    "    heatmap = cv2.resize(heatmap.numpy(), (img_array.shape[2], img_array.shape[1]))\n",
    "    heatmap = np.uint8(255 * heatmap)\n",
    "    heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)\n",
    "    return heatmap\n",
    "\n",
    "# Streamlit app\n",
    "st.title(\"Real-time Age Group and Gender Detection with Explainability\")\n",
    "\n",
    "# Sidebar for file upload and settings\n",
    "st.sidebar.header(\"Upload and Settings\")\n",
    "uploaded_file = st.sidebar.file_uploader(\"Choose an image...\", type=[\"jpg\", \"jpeg\", \"png\"])\n",
    "if uploaded_file is not None:\n",
    "    # Save uploaded file temporarily\n",
    "    image_path = \"temp_image.jpg\"\n",
    "    with open(image_path, \"wb\") as f:\n",
    "        f.write(uploaded_file.getbuffer())\n",
    "else:\n",
    "    image_path = None\n",
    "\n",
    "# Display uploaded image\n",
    "if image_path:\n",
    "    st.sidebar.image(image_path, caption=\"Uploaded Image\", use_column_width=True)\n",
    "\n",
    "# Main content\n",
    "if image_path:\n",
    "    st.subheader(\"Predictions\")\n",
    "    \n",
    "    # Age prediction\n",
    "    age_result, age_probs = predict_age_group(image_path)\n",
    "    if isinstance(age_result, str):\n",
    "        st.error(age_result)\n",
    "    else:\n",
    "        st.write(f\"Predicted Age Group: {age_result}\")\n",
    "        fig, ax = plt.subplots()\n",
    "        ax.bar(['MIDDLE', 'OLD', 'YOUNG'], age_probs)\n",
    "        ax.set_title(\"Age Group Probabilities\")\n",
    "        st.pyplot(fig)\n",
    "\n",
    "    # Gender prediction\n",
    "    gender_result = predict_gender(image_path)\n",
    "    if isinstance(gender_result, dict) and \"Error\" not in gender_result:\n",
    "        st.write(\"Gender Probabilities:\")\n",
    "        fig, ax = plt.subplots()\n",
    "        ax.pie(gender_result.values(), labels=gender_result.keys(), autopct='%1.1f%%')\n",
    "        ax.set_title(\"Gender Distribution\")\n",
    "        st.pyplot(fig)\n",
    "    else:\n",
    "        st.error(gender_result.get(\"Error\", \"Gender prediction failed\"))\n",
    "\n",
    "    # Grad-CAM for age model\n",
    "    img = Image.open(image_path).convert('RGB')\n",
    "    img_resized = img.resize(IMG_SIZE)\n",
    "    img_array = np.expand_dims(np.array(img_resized) / 255.0, axis=0)\n",
    "    heatmap = grad_cam(age_model, img_array)\n",
    "    superimposed_img = cv2.addWeighted(cv2.cvtColor(np.array(img_resized), cv2.COLOR_RGB2BGR), 0.6, heatmap, 0.4, 0)\n",
    "    st.subheader(\"Grad-CAM Heatmap (Age Model)\")\n",
    "    st.image(superimposed_img, caption=\"Grad-CAM Overlay\", use_column_width=True)\n",
    "\n",
    "    # Optional: Grad-CAM for gender (more complex, deferred)\n",
    "    st.write(\"Note: Grad-CAM for gender requires accessing DeepFace's internal model, which is not implemented here.\")\n",
    "\n",
    "# Dataset stats (optional, based on training data)\n",
    "st.sidebar.subheader(\"Dataset Statistics\")\n",
    "try:\n",
    "    csv_path = \"/mnt/data/faces_dataset/train.csv\"\n",
    "    df = pd.read_csv(csv_path)\n",
    "    df['ID'] = df['ID'].str.lower().str.replace(r'\\.jpg|\\.jpeg|\\.png', '', regex=True).str.strip()\n",
    "    image_dir = \"/mnt/data/faces_dataset/Train/\"\n",
    "    image_files = [f for f in os.listdir(image_dir) if os.path.isfile(os.path.join(image_dir, f))]\n",
    "    base_to_full = {os.path.splitext(f)[0].lower(): f for f in image_files}\n",
    "    df['filename'] = df['ID'].map(base_to_full)\n",
    "    df = df.dropna(subset=['filename'])\n",
    "    st.sidebar.write(f\"Total Valid Images: {len(df)}\")\n",
    "    st.sidebar.write(f\"Class Distribution: {df['Class'].value_counts().to_dict()}\")\n",
    "except Exception as e:\n",
    "    st.sidebar.error(f\"Error loading dataset stats: {e}\")\n",
    "\n",
    "# Cleanup\n",
    "if image_path and os.path.exists(image_path):\n",
    "    os.remove(image_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "40e2a841-745a-47d0-8f0a-f5743ea46e2c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting deepface\n",
      "  Downloading deepface-0.0.94-py3-none-any.whl.metadata (35 kB)\n",
      "Requirement already satisfied: requests>=2.27.1 in /opt/anaconda3/lib/python3.12/site-packages (from deepface) (2.32.2)\n",
      "Requirement already satisfied: numpy>=1.14.0 in /opt/anaconda3/lib/python3.12/site-packages (from deepface) (1.26.4)\n",
      "Requirement already satisfied: pandas>=0.23.4 in /opt/anaconda3/lib/python3.12/site-packages (from deepface) (2.2.2)\n",
      "Collecting gdown>=3.10.1 (from deepface)\n",
      "  Downloading gdown-5.2.0-py3-none-any.whl.metadata (5.8 kB)\n",
      "Requirement already satisfied: tqdm>=4.30.0 in /opt/anaconda3/lib/python3.12/site-packages (from deepface) (4.66.4)\n",
      "Requirement already satisfied: Pillow>=5.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from deepface) (10.3.0)\n",
      "Requirement already satisfied: opencv-python>=4.5.5.64 in /opt/anaconda3/lib/python3.12/site-packages (from deepface) (4.8.0.74)\n",
      "Requirement already satisfied: tensorflow>=1.9.0 in /opt/anaconda3/lib/python3.12/site-packages (from deepface) (2.19.0)\n",
      "Requirement already satisfied: keras>=2.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from deepface) (3.6.0)\n",
      "Collecting Flask<=2.0.2,>=1.1.2 (from deepface)\n",
      "  Downloading Flask-2.0.2-py3-none-any.whl.metadata (3.8 kB)\n",
      "Collecting werkzeug<=2.0.2 (from deepface)\n",
      "  Downloading Werkzeug-2.0.2-py3-none-any.whl.metadata (4.5 kB)\n",
      "Collecting flask-cors>=4.0.1 (from deepface)\n",
      "  Downloading flask_cors-6.0.1-py3-none-any.whl.metadata (5.3 kB)\n",
      "Collecting mtcnn>=0.1.0 (from deepface)\n",
      "  Downloading mtcnn-1.0.0-py3-none-any.whl.metadata (5.8 kB)\n",
      "Collecting retina-face>=0.0.14 (from deepface)\n",
      "  Downloading retina_face-0.0.17-py3-none-any.whl.metadata (10 kB)\n",
      "Collecting fire>=0.4.0 (from deepface)\n",
      "  Downloading fire-0.7.0.tar.gz (87 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m87.2/87.2 kB\u001b[0m \u001b[31m3.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting gunicorn>=20.1.0 (from deepface)\n",
      "  Downloading gunicorn-23.0.0-py3-none-any.whl.metadata (4.4 kB)\n",
      "Requirement already satisfied: termcolor in /opt/anaconda3/lib/python3.12/site-packages (from fire>=0.4.0->deepface) (2.5.0)\n",
      "Requirement already satisfied: Jinja2>=3.0 in /opt/anaconda3/lib/python3.12/site-packages (from Flask<=2.0.2,>=1.1.2->deepface) (3.1.4)\n",
      "Requirement already satisfied: itsdangerous>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from Flask<=2.0.2,>=1.1.2->deepface) (2.2.0)\n",
      "Requirement already satisfied: click>=7.1.2 in /opt/anaconda3/lib/python3.12/site-packages (from Flask<=2.0.2,>=1.1.2->deepface) (8.1.7)\n",
      "Requirement already satisfied: beautifulsoup4 in /opt/anaconda3/lib/python3.12/site-packages (from gdown>=3.10.1->deepface) (4.12.3)\n",
      "Requirement already satisfied: filelock in /opt/anaconda3/lib/python3.12/site-packages (from gdown>=3.10.1->deepface) (3.13.1)\n",
      "Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.12/site-packages (from gunicorn>=20.1.0->deepface) (23.2)\n",
      "Requirement already satisfied: absl-py in /opt/anaconda3/lib/python3.12/site-packages (from keras>=2.2.0->deepface) (2.1.0)\n",
      "Requirement already satisfied: rich in /opt/anaconda3/lib/python3.12/site-packages (from keras>=2.2.0->deepface) (13.3.5)\n",
      "Requirement already satisfied: namex in /opt/anaconda3/lib/python3.12/site-packages (from keras>=2.2.0->deepface) (0.0.8)\n",
      "Requirement already satisfied: h5py in /opt/anaconda3/lib/python3.12/site-packages (from keras>=2.2.0->deepface) (3.11.0)\n",
      "Requirement already satisfied: optree in /opt/anaconda3/lib/python3.12/site-packages (from keras>=2.2.0->deepface) (0.13.1)\n",
      "Requirement already satisfied: ml-dtypes in /opt/anaconda3/lib/python3.12/site-packages (from keras>=2.2.0->deepface) (0.5.3)\n",
      "Requirement already satisfied: joblib>=1.4.2 in /opt/anaconda3/lib/python3.12/site-packages (from mtcnn>=0.1.0->deepface) (1.4.2)\n",
      "Collecting lz4>=4.3.3 (from mtcnn>=0.1.0->deepface)\n",
      "  Downloading lz4-4.4.4-cp312-cp312-macosx_11_0_arm64.whl.metadata (3.8 kB)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=0.23.4->deepface) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=0.23.4->deepface) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=0.23.4->deepface) (2023.3)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.27.1->deepface) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.27.1->deepface) (3.7)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.27.1->deepface) (2.2.2)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.27.1->deepface) (2024.8.30)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow>=1.9.0->deepface) (1.6.3)\n",
      "Requirement already satisfied: flatbuffers>=24.3.25 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow>=1.9.0->deepface) (24.3.25)\n",
      "Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow>=1.9.0->deepface) (0.6.0)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow>=1.9.0->deepface) (0.2.0)\n",
      "Requirement already satisfied: libclang>=13.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow>=1.9.0->deepface) (18.1.1)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow>=1.9.0->deepface) (3.4.0)\n",
      "Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow>=1.9.0->deepface) (4.25.5)\n",
      "Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow>=1.9.0->deepface) (69.5.1)\n",
      "Requirement already satisfied: six>=1.12.0 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow>=1.9.0->deepface) (1.16.0)\n",
      "Requirement already satisfied: typing-extensions>=3.6.6 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow>=1.9.0->deepface) (4.11.0)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow>=1.9.0->deepface) (1.14.1)\n",
      "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow>=1.9.0->deepface) (1.68.0)\n",
      "Requirement already satisfied: tensorboard~=2.19.0 in /opt/anaconda3/lib/python3.12/site-packages (from tensorflow>=1.9.0->deepface) (2.19.0)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in /opt/anaconda3/lib/python3.12/site-packages (from astunparse>=1.6.0->tensorflow>=1.9.0->deepface) (0.43.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from Jinja2>=3.0->Flask<=2.0.2,>=1.1.2->deepface) (2.1.3)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /opt/anaconda3/lib/python3.12/site-packages (from tensorboard~=2.19.0->tensorflow>=1.9.0->deepface) (3.4.1)\n",
      "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from tensorboard~=2.19.0->tensorflow>=1.9.0->deepface) (0.7.2)\n",
      "Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.12/site-packages (from beautifulsoup4->gdown>=3.10.1->deepface) (2.5)\n",
      "Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /opt/anaconda3/lib/python3.12/site-packages (from requests[socks]->gdown>=3.10.1->deepface) (1.7.1)\n",
      "Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich->keras>=2.2.0->deepface) (2.2.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/anaconda3/lib/python3.12/site-packages (from rich->keras>=2.2.0->deepface) (2.15.1)\n",
      "Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/lib/python3.12/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich->keras>=2.2.0->deepface) (0.1.0)\n",
      "Downloading deepface-0.0.94-py3-none-any.whl (127 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m127.7/127.7 kB\u001b[0m \u001b[31m7.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hDownloading Flask-2.0.2-py3-none-any.whl (95 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m95.2/95.2 kB\u001b[0m \u001b[31m7.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hDownloading flask_cors-6.0.1-py3-none-any.whl (13 kB)\n",
      "Downloading gdown-5.2.0-py3-none-any.whl (18 kB)\n",
      "Downloading gunicorn-23.0.0-py3-none-any.whl (85 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m85.0/85.0 kB\u001b[0m \u001b[31m6.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hDownloading mtcnn-1.0.0-py3-none-any.whl (1.9 MB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.9/1.9 MB\u001b[0m \u001b[31m9.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m:00:01\u001b[0m\n",
      "\u001b[?25hDownloading retina_face-0.0.17-py3-none-any.whl (25 kB)\n",
      "Downloading Werkzeug-2.0.2-py3-none-any.whl (288 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m288.9/288.9 kB\u001b[0m \u001b[31m6.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25hDownloading lz4-4.4.4-cp312-cp312-macosx_11_0_arm64.whl (189 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m189.7/189.7 kB\u001b[0m \u001b[31m6.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hBuilding wheels for collected packages: fire\n",
      "  Building wheel for fire (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for fire: filename=fire-0.7.0-py3-none-any.whl size=114248 sha256=c991c2f5969b39fa0a6717aebcd6dcf5e23035edc63016c21b40921c8b85337c\n",
      "  Stored in directory: /Users/usufahmed/Library/Caches/pip/wheels/9e/5b/45/29f72e55d87a29426b04b3cfdf20325c079eb97ab74f59017d\n",
      "Successfully built fire\n",
      "Installing collected packages: werkzeug, lz4, gunicorn, fire, mtcnn, Flask, gdown, flask-cors, retina-face, deepface\n",
      "  Attempting uninstall: werkzeug\n",
      "    Found existing installation: Werkzeug 3.0.3\n",
      "    Uninstalling Werkzeug-3.0.3:\n",
      "      Successfully uninstalled Werkzeug-3.0.3\n",
      "  Attempting uninstall: lz4\n",
      "    Found existing installation: lz4 4.3.2\n",
      "    Uninstalling lz4-4.3.2:\n",
      "      Successfully uninstalled lz4-4.3.2\n",
      "  Attempting uninstall: Flask\n",
      "    Found existing installation: Flask 2.3.3\n",
      "    Uninstalling Flask-2.3.3:\n",
      "      Successfully uninstalled Flask-2.3.3\n",
      "Successfully installed Flask-2.0.2 deepface-0.0.94 fire-0.7.0 flask-cors-6.0.1 gdown-5.2.0 gunicorn-23.0.0 lz4-4.4.4 mtcnn-1.0.0 retina-face-0.0.17 werkzeug-2.0.2\n"
     ]
    }
   ],
   "source": [
    "!pip install deepface"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c36d9280-b2fc-4fc6-a14f-238eb77247c0",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
